[initial_bookmarks]
acl = "https://www.aclweb.org/anthology/search/?q=%s"
am = "https://www.amazon.com/s?k=%s"
apr = "https://www.archlinux.org/packages/?sort=&q=%s&maintainer=&flagged="
aur = "https://aur.archlinux.org/packages/?O=0&SeB=nd&K=%s&outdated=&SB=n&SO=a&PP=50&do_Search=Go"
aws = "https://console.aws.amazon.com/"
def = "https://www.lexico.com/en/definition/%s"
g = "https://www.google.com/search?q=%s&btnK"
gh = "https://github.com/search?q=%s&ref=opensearch"
gim = "https://www.google.com/search?q=%s&um=1&ie=UTF-8&hl=en&tbm=isch"
gm = "http://maps.google.com/maps?q=%s"
hub = "https://github.com"
iclr = "https://openreview.net/search?term=test&content=all&group=all&source=all"
imdb = "http://www.imdb.com/find?q=%s"
p9 = "https://plotnine.readthedocs.io/en/stable/search.html?q=%s&check_keywords=yes&area=default"
py = "https://docs.python.org/3/search.html?q=%s"
r = "https://www.reddit.com/r/%s"
sc = "https://www.semanticscholar.org/search?q=%s&sort=relevance"
wiki = "http://en.wikipedia.org/?search=%s"
ynews = "https://news.ycombinator.com/"
yt = "http://www.youtube.com/results?search_type=search_videos&search_sort=relevance&search_query=%s&search=Search"