"""add clip

Revision ID: 328d883c2a12
Revises: afd1b759e609
Create Date: 2020-06-27 17:37:06.132268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '328d883c2a12'
down_revision = 'afd1b759e609'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clips')
    # ### end Alembic commands ###
